show-case:
	grep CASE product*.log
#	grep CASE product*.log > case.log
#	git diff case.log
diff:
	git diff product*.log
head-2-diff:
	git diff HEAD~2 product*.log
running:
	tail -n2 product540-size7.log product543-size7.log product555-size7.log product557-size7.log product560-size7.log product561-size7.log
